let words = [];
let difficulty;
let letters_Scrambled;
function getDifficulty(difficulty = 1) {
    if (difficulty == 1) {
        localStorage.setItem('difficulty', '1')
        words = ['aardwolf', 'aasvogel', 'aba', 'abacinate', 'abactor', 'abaculus', 'abaft', 'abampere', 'abapical', 'abarticular', 'abasement', 'abasia', 'abask', 'abatis', 'abatjour', 'abattoir', 'abature', 'abb', 'abba', 'abbatial', 'abbozzo', 'abditive', 'abdominous', 'abducent', 'abeam', 'abear', 'abecedarian', 'abecedism', 'abele', 'abeng', 'aberdevine', 'aberuncators', 'abessive', 'abiectic', 'abigail', 'abigeus', 'abiogenesis', 'abiotrophy', 'abirritate', 'abiturient', 'abject', 'ablactation', 'ablative', 'ablator', 'ablaut', 'ablegate', 'ablepsia', 'ablow', 'abluent', 'ablution', 'ablutomania', 'abnegate', 'abodement', 'aboideau', 'abolla', 'abomasum', 'aboral', 'abord', 'aborning', 'aborticide', 'abortuary', 'aboulia', 'aboulomania', 'aboutsledge', 'abra', 'abradant', 'abraid', 'abraxas', 'abreuvoir', 'abroach', 'abrosia', 'abscind', 'abscissa', 'abscission', 'absconce', 'abseil', 'absentaneous', 'absinthial', 'absinthism', 'absit', 'absolutism', 'absolutive', 'absolutory', 'absonant', 'absorbefacient', 'absorptiometer', 'absquatulate', 'absterge', 'absurdism', 'abterminal', 'abthane', 'abulia', 'abuna', 'abusion', 'abutment', 'abvolt', 'aby', 'abyssopelagic', 'academicism', 'acanaceous', 'acantha', 'acanthous', 'acapnia', 'acapnotic', 'acariasis', 'acaricide', 'acarine', 'acarology', 'acarophobia', 'acarpous', 'acatalectic', 'acatalepsy', 'acatamathesia', 'acates', 'acatour', 'acaudate', 'acaulescent', 'accelerometer', 'accend', 'accensor', 'accentor', 'acceptilation', 'accessit', 'acciaccatura', 'accidence', 'accidentalism', 'accidie', 'accinge', 'accipiter', 'accipitral', 'accipitrine', 'accismus', 'accite', 'acclinate', 'acclivity', 'accloy', 'accolade', 'accolent', 'accollé', 'accosted', 'accoucheur', 'accoucheuse', 'accourage', 'accourt', 'accoy', 'accrementition', 'accretion', 'accubation', 'accubitum', 'accusative', 'acedia', 'aceldama', 'aceology', 'acequia', 'acerate', 'acerbate', 'acerous', 'acersecomic', 'acervate', 'acervuline', 'acescence', 'acetabulum', 'acetarious', 'acetimeter', 'achaenocarp', 'acharné', 'achene', 'achloropsia',
            'achor', 'achromatopsia', 'achroous', 'acicular', 'acidaemia', 'acidimeter', 'acidulous', 'acierate', 'acinaceous', 'acinaciform', 'aciniform', 'acinus', 'acipenser', 'ackamarackus', 'aclinic', 'acock', 'acoemeti', 'acology', 'acolous', 'acolouthic', 'acopic', 'acoria', 'acosmism', 'acouasm', 'acquest', 'acracy', 'acratia', 'acre-breadth', 'acritochromacy', 'acroamatic', 'acrocephalous', 'acrography', 'acrolith', 'acrologic', 'acromegaly', 'acronical', 'acronym', 'acronyx', 'acropathy', 'acrophobia', 'acrophonic', 'acropodium', 'acroscopic', 'acroteleutic', 'acroterion', 'acrotism', 'actinism', 'actinograph', 'actinometer', 'actinotherapy', 'acton', 'actuate', 'aculeate', 'aculeiform', 'acultomancy', 'acuminate', 'acutiator', 'acutorsion', 'acyanopsia', 'acyesis', 'acyrology', 'adactylous', 'adamantine', 'adamitism', 'adaxial', 'addax', 'addax', 'additament', 'addititious', 'addle', 'addorsed', 'adduce', 'adeciduate', 'adeem', 'adelaster', 'adelphogamy', 'ademption', 'adenalgia', 'adenia', 'adeniform', 'adenography', 'adenoid', 'adenology', 'adenotomy', 'adespota', 'adessive', 'adevism', 'adharma', 'adhibit', 'adhocracy', 'adiabatic', 'adiaphoresis', 'adiaphorism', 'adiaphoron', 'adiapneustia', 'adiathermancy', 'adipescent', 'adipic', 'adipocere', 'adipsia', 'adit', 'adjudge', 'adjutage', 'adjutant', 'adjutor', 'adjuvant', 'admanuensis', 'admaxillary', 'admeasurement', 'adminicle', 'adnascent', 'adnominal', 'adnomination', 'adnoun', 'adonise', 'adoptionism', 'adoral', 'adosculation', 'adown', 'adoxography', 'adoxy', 'adpress', 'adrogation', 'adscititious', 'adscript', 'adsorb', 'adumbrate', 'adunc', 'aduncate', 'adust', 'advection', 'advehent', 'advenient', 'adventitious', 'adventive', 'adversaria', 'adversative', 'advert', 'advertorial', 'advesperate', 'advocaat', 'advowson', 'adynamia', 'adynaton', 'adytum', 'adzebill', 'aedile', 'aedoeology', 'aegilops', 'aegis', 'aegrotat', 'aeneous', 'aeolian', 'aeolipyle', 'aeolistic', 'aeolotropy', 'aeonian', 'aepyornis', 'aerenchyma', 'aeriform', 'aerious', 'aerobe', 'aerobiology', 'aerodonetics', 'aerogenesis',
            'aerography', 'aerolite', 'aerolith', 'aerolithology', 'aerology', 'aeromancy', 'aerometer', 'aerophane', 'aerophilately', 'aerophobia', 'aerophone', 'aerophore', 'aeropleustic', 'aerostat', 'aerostatics', 'aeruginous', 'aerugo', 'aesc', 'aesopian', 'aesthesia', 'aesthesiogenic', 'aestheticism', 'aestival', 'aethrioscope', 'aeviternal', 'aeviternity', 'afebrile', 'affabulation', 'affeer', 'afferent', 'affiance', 'affine', 'afflated', 'afflatus', 'afforce', 'afforest', 'affranchise', 'affray', 'affrayer', 'affreightment', 'affreux', 'affricate', 'affronté', 'affusion', 'afore', 'afterclap', 'afterdeck', 'aftergame', 'afterguard', 'afterhand', 'afterings', 'afterpiece', 'aftershaft', 'afterwil', 'agacerie', 'agalactia', 'agalloch', 'agamist', 'agamogenesis', 'agape', 'agapeistic', 'agapet', 'agapetae', 'agapism', 'agastopia', 'agatewear', 'agathism', 'agathodaimon', 'agelast', 'agennesic', 'agenocratia', 'agentive', 'ageotropic', 'agersia', 'ageusia', 'agger', 'aggerose', 'aggiornamento', 'aggrade', 'aggrandize', 'aggrate', 'aggry', 'agio', 'agiotage', 'agist', 'agistment', 'aglet', 'agma', 'agminate', 'agnail', 'agname', 'agnation', 'agnize', 'agnomen', 'agnomination', 'agnosic', 'agnosticism', 'agnosy', 'agoge', 'agogic', 'agomphosis', 'agone', 'agonic', 'agonism', 'agonistes', 'agonistic', 'agonistics', 'agoraphobia', 'agouti', 'agowilt', 'agraffe', 'agrapha', 'agraphia', 'agravic', 'agrestic', 'agriology', 'agrize', 'agrizoiatry', 'agrobiology', 'agrology', 'agromania', 'agronomics', 'agrostography', 'agrostology', 'agrypnia', 'agrypnotic', 'aguardiente', 'agyiophobia', 'agynary', 'ahimsa', 'ahull', 'ai', 'aichmophobia', 'aiger', 'aigrette', 'aiguille', 'aileron', 'ailette', 'ailuromancy', 'ailurophilia', 'ailurophobia', 'aioli', 'airscrew', 'aischrolatry', 'aisling', 'ait', 'aitchbone', 'aiué', 'akeratophorous', 'akinesia', 'ala', 'alabamine', 'alack', 'alalia', 'alameda', 'alamode', 'alamort', 'alannah', 'alar', 'alastrim', 'alate', 'alation', 'alaudine', 'alb', 'albarello', 'albata', 'albe', 'albedo', 'albescent', 'albicant', 'albificative',
            'albion', 'albocracy', 'albolith', 'albugineous', 'alcahest', 'alcatote', 'alcine', 'alcoholometer', 'alcovinometer', 'aleatoric', 'aleberry', 'alecost', 'alectormancy', 'alectryomachy', 'alectryomancy', 'alee', 'alegar', 'alembicated', 'alepine', 'alethiology', 'aleuromancy', 'alexia', 'alexipharmic', 'alfet', 'alforge', 'algedonics', 'algefacient', 'algetic', 'algicide', 'algid', 'alginuresis', 'algolagnia', 'algology', 'algophobia', 'algor', 'algraphy', 'alible', 'alicorn', 'alidade', 'alieniloquy', 'aliform', 'aligerous', 'aliicide', 'aliped', 'aliphatic', 'aliquant', 'aliquot', 'aliter', 'aliunde', 'alk', 'alkalimeter', 'alkanet', 'allantiasis', 'allantoid', 'allative', 'allemain', 'allemande', 'alliaceous', 'allicient', 'allision', 'allocatur', 'allochthonous', 'allodic', 'allogamy', 'allogeneous', 'allography', 'allolalia', 'allonge', 'allonym', 'alloquy', 'allotheism', 'allotriophagy', 'allotropy', 'alluvion', 'allwhere', 'almacantar', 'almagest', 'almandine',
            'abide', 'abjure', 'abroad', 'adamant', 'afield', 'aforetime', 'aghast', 'agin', 'aloof', 'amiss', 'an', 'anon', 'apace', 'argent', 'arrassed', 'assuage', 'astonied', 'aught', 'bade', 'baldric', 'bannock', 'barrel', 'baseborn', 'bason', 'bay', 'bebother', 'befall', 'belie', 'benighted', 'bent', 'beset', 'besom', 'besotted', 'besotted2', 'besought', 'bier', 'billow', 'bivouac', 'blazoned', 'bond', 'booby', 'boon', 'brakes', 'brazen', 'brood', 'brood2', 'brook', 'buckler', 'bulwark', 'burg', 'burgeon', 'burnished', 'cairn', 'carcanet', 'carouse', 'carven', 'cataract', 'cesspool', 'chalcedony', 'champ', 'charger', 'chime', 'circlet', 'clamant', 'clave', 'clomb', 'cloven', 'cob', 'coëval', 'coffer', 'comely', 'commons', 'compass', 'conclave', 'concourse', 'confines', 'confusticate', 'constellate', 'cony', 'cools', 'coomb', 'coop', 'corbel', 'corslet', 'cot', 'counsels', 'covet', 'covetice', 'cozen', 'craven', 'crocks', 'culvert', 'cumbrous', 'cunning-handed', 'curdle', 'dainty', 'damask', 'darkling', 'daunt', 'declaim', 'deem', 'defile', 'defray', 'dell', 'descry', 'devices', 'dingle', 'dissemble', 'divers', 'dolven', 'doom', 'dotard', 'doughty', 'draught', 'draught2', 'drear', 'dregs', 'dry', "durstn't", 'dwimmer-crafty', 'eaves', 'eld', 'ell', 'embattled', 'embattled2', 'embrasure', 'encompass', 'ere', 'errantry', 'espy', 'essay', 'esteem', 'et', 'etten', 'ewer', 'eyot', 'faggot', 'fain', 'falter', 'fane', 'fare', 'fastness', 'fawn', 'fealty', 'feign', 'fell', 'fell2', 'fell3', 'fender', 'fetter', 'fey', 'field', 'figured', 'firth', 'flagon', 'flammifer', 'flank', 'flittermice', 'flotsam', 'flummoxed', 'footpad', 'forbear', 'forebode', 'forespeak', 'foreswear', 'forgo', 'forlorn', 'forsake', 'forsooth', 'fortnight', 'fosse', 'founder', 'fraught', 'freshet', 'furlong', 'gaffer', 'gainsay', 'gallop', 'game', 'gammer', 'garth', 'ghyll', 'gibbet', 'gimlet', 'girdle', 'girdle2', 'girt', 'glede', 'gloaming', 'glower', 'goggle', 'gorcrow', 'graven', 'greened', 'grot', 'guileful', 'gunwale', 'habergeon', 'hale', 'hame', 'hang', 'harbour', 'hardly', 'hardly2',
            'harry', 'haste', 'hauberk', 'headstall', 'hearken', 'heed', 'heedless', 'hence', 'hew', 'hither', 'hither2', 'hoar', 'hobble', 'hock', 'houseleek', 'hue', 'hummock', 'hundredweight', "hunter's", 'hythe', 'ill', 'inaureoled', 'jacinth', 'jetsam', 'keen', 'kerb', 'kindle', 'lampads', 'lave', 'lay', 'league', 'leaguer', 'leave', 'lee', 'leech', 'leechcraft', 'legendarium', 'lets', 'lief', 'liever', 'lissom', 'loath', 'lob', 'loth', 'louver', 'lustihead', 'malefactor', 'mantle', 'mar', 'march', 'marchwarden', 'mark', 'marshal', 'mattock', 'maw', 'mayhap', 'mead', 'mead2', 'meed', 'mere', 'mew', 'midge', 'minished', 'mischance', 'misgive', 'moonshine', 'muster', 'nethermost', 'nicety', 'nigh', 'nightshade', 'noisome', 'nook', 'nuncle[6][7]', 'obeisance', 'oft', 'or', 'or', 'ostler', 'ousel', 'oust', 'outworn', 'overbear', 'pallid', 'panoply', 'parapet', 'parley', 'passward', 'pate', 'pent', 'penthouse', 'perforce', 'pinion', 'plash', 'pleasance', 'pled', 'plenilune', 'portage', 'portent', 'postern', 'pricks', 'profound', 'prosy', 'provender', 'puissant', 'purloin', 'quaff', 'quail', 'raiment', 'rearguard', 'recked', 'rede', 'redound', 'redress', 'reft', 'rent', 'repair', 'respite', 'revelry', 'rick', 'rill', 'rondured', 'rude', 'rue', 'rumour', 'ruth', 'sable', 'sallow', 'saps', 'sate', 'save', 'seamews', 'selenites', 'semblance', 'shade', 'shallop', 'shank', 'share', 'sheaf', 'shoal', 'shore', 'shun', 'sister-son', 'sledge-blows', 'slot', 'slowcoach', 'sluggard', 'smite', 'snuff', 'sojourn', 'sooth', 'sortie', 'spinney', 'sprent', 'sprite(s)', 'stead', 'stem', 'stock', 'stoop', 'straightway', 'strait', 'straitly', 'strand', 'stricken', 'suaded', 'succour', 'sunder', 'surname', 'sward', 'swart', 'swarthy', 'swath', 'swoon', 'tarn', 'tarry', 'thanksgiving-', 'thenceforward', 'thither', 'thraldom', 'thrall', 'thrawn', 'thrawn2', 'throe', 'throve', 'thwart', 'tidings', 'tipsy', 'tithe', 'toils', 'toothsome', 'tors', 'toss-pot', 'tracery', 'traffic', 'trammels',
            , 'traverse', 'trillups,', 'trove', 'truncheon', 'tryst', 'tumult', 'tunic', 'tuppence', 'turnkey', 'tussock', 'twine', 'umbel', 'unblazoned', 'umbraged', 'ungentle', 'unquiet', 'unsated', 'unsullied', 'upbraid', 'upheave', 'vale', 'varmint', 'vassal', 'vie', 'vigil', 'viol', 'waif', 'wain', 'wan', 'wards', 'ware', 'waver', 'waver2', 'wax', 'waylay', 'wayward', 'web(s)', 'wellnigh', 'weregild', 'wheedle', 'whelm', 'whence', 'whereat', 'wherefore', 'whet', 'whickering', 'whitethorn', 'whither', 'wildered', 'wile', 'wizened', 'wold', 'wont', 'worrit', 'worst', 'wrack', 'wrack2', 'wraith', 'wreathe', 'wrest', 'writhen', 'wroth', 'yammer', 'yoke', 'yonder', 'yore', 'zenith',
            'Accismus', 'Acumen', 'Anachronistic', 'Anthropomorphize', 'Apricate', 'Bastion', '(verb)', 'Burgeon', 'Convivial', 'Conundrum', 'Credulity', 'Crepuscular', 'Edify', 'Effete', 'Egregious', 'Eschew', 'Fatuous', 'Fractious', 'Galvanize', 'Imperious', 'Impetus', 'Insouciant', 'Interlocutor', 'Lionize', 'Melange', 'Metanoia', 'Myriad', 'Noisome', 'Obfuscate', 'Odious', 'Ostensibly', 'Paucity', 'Penultimate', 'Pernicious', 'Perspicacious', 'Philistine', 'Prevaricate', 'Rapscallion', 'Sagacious', 'Sanguine', 'Serendipity', 'Solipsist', 'Synecdoche', 'Timorous', 'Ubiquitous', 'Uhtceare', 'Ultracrepidarian', 'Verisimilitude', 'Visceral', 'Zeugma',
            'aa', 'abaya', 'abomasum', 'absquatulate', 'adscititious', 'afreet', 'Albertopolis', 'alcazar', 'amphibology', 'amphisbaena', 'anfractuous', 'anguilliform', 'apoptosis', 'apple-knocker', 'argle-bargle', 'Argus-eyed', 'argute', 'ariel', 'aristotle', 'aspergillum', 'astrobleme', 'Attic salt', 'autotomy', 'badmash', 'bandoline', 'bardolatry', 'Barmecide', 'barn burner', 'bashment', 'bawbee', 'benthos', 'bergschrund', 'bezoar', 'bibliopole', 'bichon frise', 'bilboes', 'bindlestiff', 'bingle', 'blatherskite', 'bleeding edge', 'blind pig', 'bobsy-die', 'boffola', 'boilover', 'borborygmus', 'breatharian', 'Brobdingnagian', 'bruxism', 'bumbo', 'burnsides', 'cacoethes', 'callipygian', 'callithumpian', 'camisado', 'canorous', 'cantillate', 'carphology', 'catoptromancy', 'cereology', 'cerulean', 'chad', 'chalkdown', 'chanticleer', 'chiliad', 'chump change', 'claggy', 'clepsydra', 'colporteur', 'comess', 'commensalism', 'comminatory', 'concinnity', 'congius', 'conniption', 'constellate', 'coprolalia', 'coriaceous', 'couthy', 'criticaster', 'crore', 'crottle', 'croze', 'cryptozoology', 'cudbear', 'cupreous', 'cyanic', 'cybersquatting', 'dariole', 'deasil', 'decubitus', 'deedy', 'defervescence', 'deglutition', 'degust', 'deipnosophist', 'deracinate', 'deterge', 'didi', 'digerati', 'dight', 'discobolus', 'disembogue', 'disenthral', 'divagate', 'divaricate', 'donkey engine', 'donkeyman', 'doryphore', 'dotish', 'douceur', 'draff', 'dragoman', 'dumbsize', 'dwaal', 'ecdysiast', 'edacious', 'effable', 'emacity', 'emmetropia', 'empasm', 'ensorcell', 'entomophagy', 'erf', 'ergometer', 'erubescent', 'e-tailer', 'etui', 'eucatastrophe', 'eurhythmic', 'eviternity', 'exequies', 'exsanguine', 'extramundane', 'eye candy', 'eyewater', 'famulus', 'fankle', 'fipple', 'flatline', 'flews', 'floccinaucinihilipilification', 'flocculent', 'force-ripe', 'forehanded', 'frondeur', 'fugacious', 'funambulist', 'furuncle', 'fuscous', 'futhark', 'futz', 'gaberlunzie', 'gaita', 'galligaskins', 'gallus', 'gasconade', 'glabrous', 'glaikit', 'gnathic', 'gobemouche', 'goodfella', 'guddle', 'habile',
            'hallux', 'haruspex', 'higgler', 'hinky', 'hoddy-noddy', 'hodiernal', 'hoggin', 'hongi', 'howff', 'humdudgeon', 'hunt-and-peck', 'hwyl', 'illywhacker', 'incrassate', 'incunabula', 'ingurgitate', 'inspissate', 'inunct', 'jumbuck', 'jumentous', 'jungli', 'karateka', 'keek', 'kenspeckle', 'kinnikinnick', 'kylie', 'labarum', 'lablab', 'lactarium', 'liripipe', 'loblolly', 'lobola', 'logomachy', 'lollygag', 'luculent', 'lycanthropy', 'macushla', 'mallam', 'mamaguy', 'martlet', 'mazel tov', 'meacock', 'merkin', 'merrythought', 'mim', 'mimsy', 'minacious', 'minibeast', 'misogamy', 'mistigris', 'mixologist', 'mollitious', 'momism', "monkey's wedding", 'monorchid', 'moonraker', 'mouse potato', 'mudlark', 'muktuk', 'mumpsimus', 'nacarat', 'nagware', 'nainsook', 'natation', 'nesh', 'netizen', 'noctambulist', 'noyade', 'nugacity', 'nympholepsy', 'obnubilate', 'ogdoad', 'omophagy', 'omphalos', 'onolatry', 'o-o', 'operose', 'opsimath', 'orectic', 'orrery', 'ortanique', 'otalgia', 'oxter', 'paludal', 'Pantagruelian', 'panurgic', 'parapente', 'paraph', 'patulous', 'pavonine', 'pedicular', 'peely-wally', 'peever', 'periapt', 'petcock', 'peterman', 'pettitoes', 'piacular', 'pilgarlic', 'pinguid', 'piscatorial', 'pleurodynia', 'plew', 'pneumonoul­tramicrosc­opicsilico­volcanocon­iosis', 'pogey', 'pollex', 'pooter', 'portolan', 'posology', 'possident', 'pother', 'pre-loved', 'presenteeism', 'previse', 'probang', 'prosopagnosia', 'puddle jumper', 'puddysticks', 'pyknic', 'pyroclastic', 'ragtop', 'ratite', 'rawky', 'razzia', 'rebirthing', 'resurrection man', 'retiform', 'rhinoplasty', 'rubiginous', 'rubricate', 'rude boy', 'rug rat', 'rumpot', 'sangoma', 'sarmie', 'saucier', 'saudade', 'scofflaw', 'screenager', 'scrippage', 'selkie', 'serac', 'sesquipedalian', 'shallop', 'shamal', 'shavetail', 'shippon', 'shofar', 'skanky', 'skelf', 'skimmington', 'skycap', 'snakebitten', 'snollygoster', 'sockdolager', 'solander', 'soucouyant', 'soul case', 'soul catcher', 'spaghettification', 'spitchcock', 'splanchnic', 'spurrier', 'stercoraceous', 'sternutator', 'stiction', 'strappado', 'strigil',
            'struthious', 'studmuffin', 'stylite', 'subfusc', 'submontane', 'succuss', 'sudd', 'suedehead', 'sun-grazing', 'superbious', 'superette', 'taniwha', 'tappen', 'tellurian', 'testudo', 'thalassic', 'thaumatrope', 'thirstland', 'thrutch', 'thurifer', 'tiffin', 'tigon', 'tokoloshe', 'toplofty', 'transpicuous', 'triskaidekaphobia', 'triskelion', 'tsantsa', 'turbary', 'ulu', 'umbriferous', 'uncinate', 'uniped', 'uroboros', 'ustad', 'vagarious', 'velleity', 'verjuice', 'vicinal', 'vidiot', 'vomitous', 'wabbit', 'waitron', 'wakeboarding', 'wayzgoose', 'winebibber', 'wish book', 'wittol', 'woopie', 'wowser', 'xenology', 'ylem', 'zetetic', 'zoolatry', 'zopissa', 'zorro', 'Zyrian',];
    }
    if (difficulty == 2) {
        localStorage.setItem('difficulty', '2')
        words = ['abaft', 'abate', 'abbey', 'abbot', 'abhor', 'abide', 'abler',
            + 'abode', 'about', 'above', 'abuse', 'abyss', 'ached', 'aches', 'acids', 'acorn', 'acres',
            + 'acrid', 'acted', 'actor', 'acute', 'adage', 'adapt', 'added', 'adder', 'adept', 'adieu',
            + 'admit', 'adobe', 'adopt', 'adore', 'adorn', 'adult', 'aegis', 'aeons', 'affix', 'afire',
            + 'afoot', 'after', 'again', 'agape', 'agate', 'agent', 'agile', 'aging', 'aglow', 'agony',
            + 'agree', 'ahead', 'aided', 'aides', 'ailed', 'aimed', 'aired', 'aisle', 'alarm', 'album',
            + 'alder', 'alias', 'alibi', 'alien', 'alike', 'alive', 'allay', 'alley', 'allot', 'allow',
            + 'alloy', 'aloes', 'aloft', 'alone', 'along', 'aloof', 'aloud', 'alpha', 'altar', 'alter',
            + 'altos', 'amass', 'amaze', 'amber', 'amble', 'amend', 'amigo', 'amiss', 'amity', 'among',
            'amour', 'ample', 'anvil', 'apace', 'apart', 'aping',
            'appal', 'apple', 'apply', 'apron', 'aptly', 'areas', 'arena', 'argue', 'arise', 'armed',
            'aroma', 'arose', 'array', 'arrow', 'arson', 'ashen', 'ashes', 'aside', 'asked', 'askew',
            'aspen', 'assay', 'asses', 'asset', 'aster', 'astir', 'atlas', 'atoll', 'atoms', 'atone',
            'attar', 'attic', 'audio', 'audit', 'auger', 'aught', 'augur', 'aunts', 'auras', 'autos',
            'avail', 'avers', 'avert', 'avoid', 'avows', 'awake', 'award', 'aware', 'awful',
            'awoke', 'axiom', 'axles', 'azure', 'babel', 'babes', 'backs', 'bacon', 'badge', 'badly',
            'baggy', 'baits', 'baize', 'baked', 'baker', 'bales', 'balls', 'balmy', 'banal', 'bands',
            'bandy', 'bangs', 'banjo', 'banks', 'banns', 'barbs', 'bards', 'bared', 'barge', 'barks',
            'barns', 'baron', 'basal', 'based', 'baser', 'bases', 'basic', 'basil', 'basin', 'basis',
            'basso', 'baste', 'batch', 'bated', 'bathe', 'baths', 'baton', 'bayou', 'beach', 'beads',
            'beady', 'beaks', 'belie', 'belle',
            'bells', 'belly', 'below', 'belts', 'bench', 'bends', 'bergs', 'berry', 'berth', 'beryl',
            'beset', 'besom', 'bevel', 'bible', 'bided', 'bides', 'bight', 'bigot', 'bilge', 'bills',
            'brats', 'brave', 'bravo', 'brawl', 'brawn', 'bread', 'briar', 'bribe', 'brick', 'bride', 'brief', 'brier', 'brigs',
            'cloth', 'cloud', 'clout', 'clove', 'clown', 'clubs', 'cluck', 'clues', 'clump', 'clung', 'coach', 'coals', 'coast', 'coats', 'cobra', 'cocks', 'cocoa', 'codes', 'coils', 'coins', 'colds', 'colic', 'colon', 'colts', 'combs', 'comer', 'comes', 'comet', 'comic', 'comma', 'conch', 'cones',
            'drays', 'dread', 'dream', 'dregs', 'dress', 'dried', 'drier', 'dries', 'drift', 'drill', 'drily', 'drink', 'drips', 'drive', 'droll', 'drone', 'droop', 'drops', 'dross', 'drove', 'drown', 'drugs', 'drums', 'drunk', 'dryly', 'ducal', 'ducat', 'duchy', 'ducks', 'ducts', 'duels', 'duets', 'dukes', 'dully', 'dummy', 'dumps', 'dumpy', 'dunce', 'dunes', 'dunno', 'duped', 'dupes', 'dusky', 'dusty', 'dwarf', 'dwell', 'dwelt', 'dying', 'dykes', 'eager', 'eagle', 'earls', 'early', 'earns', 'earth', 'eased', 'easel', 'eases', 'eaten', 'eater', 'eaves', 'ebbed', 'ebony', 'edged', 'edges', 'edict', 'edify', 'eerie', 'egged', 'eight', 'eject', 'elate', 'elbow', 'elder', 'elect', 'elegy', 'elfin', 'elite', 'elope', 'elude', 'elves', 'email', 'emits', 'empty', 'enact', 'ended', 'endow', 'enemy', 'enjoy', 'ennui', 'enrol', 'ensue', 'enter', 'entry', 'envoy', 'epics', 'epoch', 'equal', 'equip', 'erase', 'erect', 'erred', 'error', 'essay', 'ether', 'ethic', 'evade', 'event', 'every', 'evils', 'evoke', 'exact', 'exalt', 'excel', 'exert', 'exile', 'exist', 'exits', 'expel', 'extol', 'extra', 'exult', 'eying', 'eyrie', 'fable', 'faced', 'faces', 'facts', 'faded', 'fades', 'fails', 'faint', 'fairs', 'fairy', 'faith', 'fakir', 'falls', 'famed', 'fancy', 'fangs', 'farce', 'fared', 'fares', 'farms', 'fasts', 'fatal', 'fated', 'fates', 'fatty', 'fault', 'fauna', 'fauns', 'fawns', 'fears', 'feast', 'feats', 'feeds', 'feels', 'feign', 'feint', 'fells', 'felon', 'fence', 'feral', 'ferns', 'ferry', 'feted', 'fetid', 'fetus', 'feuds', 'fever', 'fewer', 'fiche', 'fiefs', 'field', 'fiend', 'fiery', 'fifes', 'fifth', 'fifty', 'fight', 'filch', 'filed', 'files', 'filet', 'fills', 'filly', 'films', 'filmy', 'filth', 'final', 'finch', 'finds', 'fined', 'finer', 'fines', 'finis', 'finny', 'fiord', 'fired', 'fires', 'firms', 'first', 'fishy', 'fists', 'fitly', 'fives', 'fixed', 'fixer', 'fixes', 'fjord', 'flags', 'flail', 'flair', 'flake', 'flaky', 'flame', 'flank', 'flaps', 'flare', 'flash', 'flask', 'flats', 'flaws', 'fleas', 'fleck', 'flees', 'fleet', 'flesh', 'flick', 'flier', 'flies', 'fling', 'flint', 'flirt', 'flits', 'float', 'flock', 'floes', 'flood', 'floor', 'flora',
            'floss', 'flour', 'flout', 'flown', 'flows', 'flues', 'fluff', 'fluid', 'fluke', 'flume', 'flung', 'flush', 'flute', 'flyer', 'foams', 'foamy', 'focal', 'foggy', 'foils', 'foist', 'folds', 'folio', 'folks', 'folly', 'foods', 'fools', 'foray', 'force', 'fords', 'forge', 'forgo', 'forks', 'forms', 'forte', 'forth', 'forts', 'forty', 'forum', 'found', 'fount', 'fours', 'fowls', 'foxes', 'foyer', 'frail', 'frame', 'franc', 'frank', 'fraud', 'freak', 'freed', 'freer', 'frees', 'fresh', 'frets', 'friar', 'fried', 'frill', 'frisk', 'frock', 'frogs', 'frond', 'front', 'frost', 'froth', 'frown', 'froze', 'fruit', 'fudge', 'fuels', 'fugue', 'fully', 'fumed', 'fumes', 'funds', 'fungi', 'funny', 'furry', 'furze', 'fused', 'fuses', 'fussy', 'fuzzy', 'gable', 'gaily', 'gains', 'gales', 'galls', 'games', 'gamin', 'gamma', 'gamut', 'gangs', 'gaped', 'gapes', 'gases', 'gasps', 'gates', 'gaudy', 'gauge', 'gaunt', 'gauze', 'gauzy', 'gavel', 'gawky', 'gayer', 'gayly', 'gazed', 'gazer', 'gazes', 'gears', 'geese', 'genie', 'genii', 'genre', 'gents', 'genus', 'germs', 'ghost', 'giant', 'gibes', 'giddy', 'gifts', 'gilds', 'gills', 'gimme', 'gipsy', 'girds', 'girls', 'girth', 'given', 'gives', 'glade', 'gland', 'glare', 'glass', 'glaze', 'gleam', 'glean', 'glens', 'glide', 'glint', 'gloat', 'globe', 'gloom', 'glory', 'gloss', 'glove', 'glows', 'glued', 'gnash', 'gnats', 'gnaws', 'gnome', 'goads', 'goals', 'goats', 'godly', 'going', 'golly', 'gongs', 'gonna', 'goods', 'goody', 'goose', 'gored', 'gorge', 'gorse', 'gotta', 'gouge', 'gourd', 'gouty', 'gowns', 'grabs', 'grace', 'grade', 'graft', 'grain', 'grams', 'grand', 'grant', 'grape', 'graph', 'grasp', 'grass', 'grate', 'grave', 'gravy', 'graze', 'great', 'greed', 'green', 'greet', 'greys', 'grief', 'grill', 'grime', 'grimy', 'grind', 'grins', 'gripe', 'grips', 'grist', 'groan', 'groin', 'groom', 'grope', 'gross', 'group', 'grove', 'growl', 'grown', 'grows', 'grubs', 'gruel', 'gruff', 'grunt', 'guano', 'guard', 'guess', 'guest', 'guide', 'guild',
            'halts', 'halve', 'hands', 'handy', 'hangs', 'happy', 'hardy', 'harem', 'hares', 'harms', 'harps', 'harpy', 'harry', 'harsh', 'harts', 'haste', 'hasty', 'hatch', 'hated', 'hater', 'hauls', 'haven', 'havoc', 'hawks', 'hazel', 'heads', 'heady', 'heals', 'heaps', 'heard', 'hears', 'heart', 'heath', 'heats', 'heave', 'heavy', 'hedge', 'heeds', 'heels', 'heirs', 'helix', 'hello', 'helms', 'helps', 'hence', 'herbs', 'herds', 'heron', 'heros', 'hewed', 'hides', 'hills', 'hilly', 'hilts', 'hinds', 'hinge', 'hints', 'hired', 'hires', 'hitch', 'hives', 'hoard', 'hoary', 'hobby', 'hoist', 'holds', 'holes', 'holly', 'homes', 'honey', 'hoods', 'hoofs', 'hooks', 'hoops', 'hoots', 'hoped', 'hopes', 'horde', 'horns', 'horny', 'horse', 'hosts', 'hotel', 'hotly', 'hound', 'hours', 'house', 'hovel', 'hover', 'howls', 'hulks', 'hulls', 'human', 'humid', 'humps', 'humus', 'hunch', 'hunts', 'hurls', 'hurry', 'hurts', 'husks', 'husky', 'hussy', 'hydra', 'hyena', 'hymns', 'icily', 'icing', 'ideal', 'ideas', 'idiom', 'idiot', 'idled', 'idler', 'idols', 'idyll', 'igloo', 'image', 'imbue', 'impel', 'imply', 'inane', 'incur', 'index', 'inept', 'inert', 'infer', 'ingot', 'inlet', 'inner', 'inter', 'inure', 'irate', 'irked', 'irons', 'irony', 'isles', 'islet', 'issue', 'items', 'ivory', 'jacks', 'jaded', 'jails', 'jaunt', 'jeans', 'jeers', 'jelly', 'jerks', 'jerky', 'jests', 'jetty', 'jewel', 'jiffy', 'joins', 'joint', 'joked', 'joker', 'jokes', 'jolly', 'joust', 'joyed', 'judge', 'juice', 'juicy', 'jumps', 'junks', 'junta', 'juror', 'karma', 'keels', 'keeps', 'ketch', 'keyed', 'khaki', 'kicks', 'kills', 'kinda', 'kinds', 'kings', 'kiosk', 'kites', 'knack', 'knave', 'knead', 'kneel', 'knees', 'knell', 'knelt', 'knife', 'knits', 'knobs', 'knock', 'knoll', 'knots', 'known', 'knows', 'label', 'laced', 'laces', 'lacks', 'laden', 'ladle', 'lager', 'lairs', 'laity', 'lakes', 'lambs', 'lamed', 'lames', 'lamps', 'lance', 'lands', 'lanes', 'lanky', 'lapel', 'lapse', 'larch', 'large', 'largo', 'larks', 'larva',
            'leave', 'ledge', 'leech', 'leeks', 'legal', 'lemme', 'lemon', 'lends', 'leper', 'levee', 'level', 'lever', 'liars', 'libel', 'licks', 'liege', 'liens', 'lifts', 'light', 'liked', 'liken', 'liker', 'likes', 'lilac', 'limbo', 'limbs', 'limes', 'limit', 'lined', 'linen', 'liner', 'lines', 'lingo', 'links', 'lions', 'lists', 'lithe', 'lived', 'liver', 'lives', 'livid', 'llama', 'loads', 'loamy', 'loans', 'loath', 'lobby', 'lobes', 'local', 'locks', 'locus', 'lodge', 'lofty', 'loges', 'logic', 'login', 'loins', 'longs', 'looks', 'looms', 'loons', 'loops', 'loose', 'lords', 'loser', 'loses', 'lotus', 'louse', 'lousy', 'loved', 'lover', 'loves', 'lowed', 'lower', 'lowly', 'loyal', 'lucid', 'lucky', 'lulls', 'lumps', 'lumpy', 'lunar', 'lunch', 'lunge', 'lungs', 'lurch', 'lured', 'lures', 'lurid', 'lurks', 'lusts', 'lusty', 'lutes', 'lying', 'lymph', 'lynch', 'lyric', 'maces', 'madam', 'madly', 'magic', 'maids', 'mails', 'mains', 'maize', 'major', 'maker', 'makes', 'males', 'mamma', 'manes', 'manga', 'mange', 'mango', 'mangy', 'mania', 'manly', 'manna', 'manor', 'manse', 'maple', 'march', 'mares', 'marks', 'marry', 'marsh', 'marts', 'masks', 'mason', 'masts', 'match', 'mated', 'mates', 'mauve', 'maxim', 'maybe', 'mayor', 'mazes', 'meals', 'mealy', 'means', 'meant', 'meats', 'medal', 'media', 'meets', 'melon', 'melts', 'memes', 'mends', 'menus', 'mercy', 'meres', 'merge', 'merit', 'merry', 'mesas', 'metal', 'meted', 'meter', 'mewed', 'midst', 'miens', 'might', 'milch', 'miles', 'milky', 'mills', 'mimes', 'mimic', 'mince', 'minds', 'mined', 'miner', 'mines', 'minor', 'mints', 'minus', 'mirth', 'miser', 'mists', 'mites', 'mixed', 'mixes', 'moans', 'moats', 'mocks', 'model', 'modem', 'modes', 'moist', 'molar', 'moles', 'momma', 'money', 'monks', 'month', 'moods', 'moody', 'moons', 'moors', 'moose', 'moped', 'moral', 'mores', 'mossy', 'motes', 'moths', 'motif', 'motor', 'motto', 'mound', 'mount', 'mourn', 'mouse', 'mouth', 'moved', 'mover', 'moves', 'movie', 'mowed', 'mower', 'mucus', 'muddy', 'mules', 'multi', 'mummy', 'mumps', 'munch', 'mural', 'murky', 'mused', 'muses', 'music', 'musky', 'musty', 'muted', 'mutes', 'myrrh', 'myths', 'nabob', 'nails', 'naive',
            'naked', 'named', 'names', 'nasal', 'nasty', 'natal', 'natty', 'naval', 'navel', 'naves', 'nears', 'necks', 'needs', 'needy', 'neigh', 'nerve', 'nests', 'never', 'newer', 'newly', 'nicer', 'niche', 'niece', 'night', 'ninny', 'noble', 'nobly', 'noise', 'noisy', 'nomad', 'nonce', 'nooks', 'noose', 'north', 'nosed', 'noses', 'notch', 'noted', 'notes', 'nouns', 'novel', 'nudge', 'nurse', 'nymph', 'oaken', 'oakum', 'oases', 'oasis', 'oaten', 'oaths', 'obese', 'obeys', 'occur', 'ocean', 'ochre', 'odder', 'oddly', 'odium', 'offal', 'offer', 'often', 'oiled', 'olden', 'older', 'omens', 'omits', 'onion', 'onset', 'oozed', 'oozes', 'opals', 'opens', 'opera', 'opine', 'opium', 'optic', 'orbit', 'order', 'organ', 'osier', 'other', 'otter', 'ought', 'ounce', 'outdo', 'outer', 'ovals', 'ovary', 'ovens', 'overt', 'owing', 'owned', 'owner', 'oxide', 'ozone', 'paces', 'packs', 'paddy', 'padre', 'paean', 'pagan', 'pages', 'pails', 'pains', 'paint', 'pairs', 'paled', 'paler', 'pales', 'palms', 'palmy', 'palsy', 'panel', 'panes', 'pangs', 'panic', 'pansy', 'pants', 'papal', 'papas', 'paper', 'pared', 'parka', 'parks', 'parry', 'parse', 'parts', 'party', 'pasha', 'paste', 'pasty', 'patch', 'pates', 'paths', 'patio', 'pause', 'paved', 'pawed', 'pawns', 'payed', 'payer', 'peace', 'peach', 'peaks', 'peals', 'pearl', 'pears', 'pease', 'pecks', 'pedal', 'peeps', 'peers', 'pelts', 'penal', 'pence', 'penis', 'penny', 'peons', 'perch', 'peril', 'pesky', 'pesos', 'pests', 'petal', 'petty', 'phase', 'phial', 'phone', 'photo', 'piano', 'picks', 'piece', 'piers', 'piety', 'pigmy', 'pikes', 'piled', 'piles', 'pills', 'pilot', 'pinch', 'pined', 'pines', 'pinks', 'pinto', 'pints', 'pious', 'piped', 'piper', 'pipes', 'pique', 'pitch', 'pithy', 'pivot', 'place', 'plaid', 'plain', 'plait', 'plane', 'plank', 'plans', 'plant', 'plate', 'plays', 'plaza', 'plead', 'pleas', 'plied', 'plies', 'plots', 'pluck', 'plugs', 'plumb', 'plume', 'plums', 'plush', 'podia', 'poems', 'poesy', 'poets', 'point', 'poise', 'poked', 'poker', 'pokes', 'polar', 'poles', 'polka', 'polls', 'ponds', 'pools', 'popes', 'poppa', 'poppy', 'porch', 'pored', 'pores', 'ports', 'posed', 'poser', 'poses', 'posse', 'posts',
            'pouch', 'pound', 'pours', 'power', 'prank', 'prate', 'prays', 'press', 'preys', 'price', 'prick', 'pride', 'pried', 'pries', 'prime', 'prior', 'prism', 'privy', 'prize', 'probe', 'prone', 'proof', 'props', 'prose', 'prosy', 'proud', 'prove', 'prowl', 'prows', 'proxy', 'prude', 'prune', 'psalm', 'pshaw', 'pudgy', 'puffs', 'puffy', 'pulls', 'pulpy', 'pulse', 'pumps', 'punch', 'pupil', 'puppy', 'puree', 'purer', 'purge', 'purse', 'pussy', 'putty', 'quack', 'quaff', 'quail', 'quake', 'qualm', 'quart', 'quasi', 'quays', 'queen', 'queer', 'quell', 'query', 'quest', 'queue', 'quick', 'quiet', 'quill', 'quilt', 'quips', 'quire', 'quite', 'quits', 'quota', 'quote', 'quoth', 'rabbi', 'rabid', 'raced', 'racer', 'races', 'racks', 'radii', 'radio', 'rafts', 'raged', 'rages', 'raids', 'rails', 'rains', 'rainy', 'raise', 'rajah', 'raked', 'rakes', 'rally', 'ranch', 'range', 'ranks', 'rapid', 'rarer', 'rares', 'rated', 'rates', 'ratio', 'raved', 'raven', 'raves', 'rayon', 'razed', 'razor', 'reach', 'react', 'reads', 'ready', 'realm', 'reals', 'reams', 'reaps', 'rears', 'rebel', 'rebus', 'rebut', 'recur', 'reeds', 'reedy', 'reefs', 'reeks', 'reels', 'reeve', 'refer', 'refit', 'regal', 'reign', 'reins', 'relax', 'relay', 'relic', 'remit', 'rends', 'renew', 'rents', 'repay', 'repel', 'reply', 'reset', 'resin', 'rests', 'revel', 'revue', 'rheum', 'rhyme', 'ricks', 'rider', 'rides', 'ridge', 'rifle', 'rifts', 'right', 'rigid', 'riled', 'rills', 'rimes', 'rings', 'rinse', 'riots', 'ripen', 'riper', 'risen', 'riser', 'rises', 'risks', 'risky', 'rites', 'rival', 'riven', 'river', 'rivet', 'roads', 'roams', 'roars', 'roast', 'robed', 'robes', 'robin', 'rocks', 'rocky', 'rogue', 'roles', 'rolls', 'roman', 'roofs', 'rooks', 'rooms', 'roomy', 'roost', 'roots', 'roped', 'ropes', 'roses', 'rosin', 'rouge', 'rough', 'round', 'rouse', 'route', 'routs', 'roved', 'rover', 'rowdy', 'rowed', 'royal', 'ruder', 'ruffs', 'ruins', 'ruled', 'ruler', 'rules', 'runes', 'rungs', 'rupee', 'rural', 'ruses', 'sable', 'sabre', 'sacks', 'sadly', 'safer', 'sagas', 'sages', 'sahib', 'sails', 'saint', 'saith', 'salad', 'sales', 'sally', 'salon', 'salsa', 'salts', 'salty', 'salve', 'salvo',
            'sands', 'sandy', 'saner', 'sated', 'satin', 'satyr', 'sauce', 'saucy', 'saved', 'saves', 'sawed', 'scald', 'scale', 'scalp', 'scaly', 'scamp', 'scans', 'scant', 'scare', 'scarf', 'scars', 'scene', 'scent', 'scion', 'scoff', 'scold', 'scoop', 'scope', 'score', 'scorn', 'scour', 'scout', 'scowl', 'scrap', 'screw', 'scrip', 'scrub', 'scull', 'seals', 'seams', 'seamy', 'seats', 'sects', 'sedan', 'sedge', 'seeds', 'seedy', 'seeks', 'seems', 'seers', 'seize', 'sells', 'semen', 'sends', 'sense', 'serfs', 'serge', 'serum', 'serve', 'seven', 'sever', 'sewed', 'sewer', 'sexes', 'shack', 'shade', 'shady', 'shaft', 'shake', 'shaky', 'shale', 'shall', 'shalt', 'shame', 'shams', 'shank', 'shape', 'share', 'shark', 'sharp', 'shave', 'shawl', 'sheaf', 'shear', 'sheds', 'sheen', 'sheep', 'sheer', 'sheet', 'sheik', 'shelf', 'shell', 'shied', 'shift', 'shine', 'shins', 'shiny', 'ships', 'shire', 'shirk', 'shirt', 'shoal', 'shock', 'shoes', 'shone', 'shook', 'shoon', 'shoot', 'shops', 'shore', 'shorn', 'short', 'shots', 'shout', 'shove', 'shown', 'shows', 'showy', 'shred', 'shrew', 'shrub', 'shrug', 'shuns', 'shuts', 'shyly', 'sibyl', 'sided', 'sides', 'siege', 'sieve', 'sighs', 'sight', 'sigma', 'signs', 'silks', 'silky', 'sills', 'silly', 'since', 'sinew', 'singe', 'sings', 'sinks', 'siren', 'sires', 'sites', 'sixes', 'sixth', 'sixty', 'sized', 'sizes', 'skate', 'skein', 'skies', 'skiff', 'skill', 'skims', 'skins', 'skips', 'skirt', 'skulk', 'skull', 'skunk', 'slabs', 'slack', 'slags', 'slain', 'slake', 'slang', 'slant', 'slaps', 'slash', 'slate', 'slats', 'slave', 'slays', 'sleds', 'sleek', 'sleep', 'sleet', 'slept', 'slice', 'slick', 'slide', 'slily', 'slime', 'slimy', 'sling', 'slink', 'slips', 'slits', 'sloop', 'slope', 'slops', 'sloth', 'slugs', 'slump', 'slums', 'slung', 'slunk', 'slush', 'slyly', 'smack', 'small', 'smart', 'smash', 'smear', 'smell', 'smelt', 'smile', 'smirk', 'smite', 'smith', 'smock', 'smoke', 'smoky', 'smote', 'snack', 'snags', 'snail', 'snake', 'snaky', 'snaps', 'snare', 'snarl', 'sneak', 'sneer', 'sniff', 'snipe', 'snobs', 'snore', 'snort', 'snout', 'snows', 'snowy', 'snuff', 'soapy', 'soars', 'sober', 'socks', 'sofas', 'soggy', 'soils',
            'solar', 'soles', 'solid', 'solos', 'solve', 'songs', 'sonny', 'sooth', 'sooty', 'sores', 'sorry', 'sorts', 'sough', 'souls', 'sound', 'soups', 'souse', 'south', 'sowed', 'sower', 'space', 'spade', 'spake', 'spank', 'spans', 'spare', 'spark', 'spars', 'spasm', 'spawn', 'speak', 'spear', 'speck', 'speed', 'spell', 'spelt', 'spend', 'spent', 'sperm', 'spice', 'spicy', 'spied', 'spies', 'spike', 'spill', 'spilt', 'spine', 'spins', 'spiny', 'spire', 'spite', 'spits', 'split', 'spoil', 'spoke', 'spook', 'spool', 'spoon', 'spoor', 'spore', 'sport', 'spots', 'spout', 'spray', 'spree', 'sprig', 'spunk', 'spurn', 'spurs', 'spurt', 'squad', 'squat', 'squaw', 'stabs', 'stack', 'staff', 'stage', 'stags', 'staid', 'stain', 'stair', 'stake', 'stale', 'stalk', 'stall', 'stamp', 'stand', 'stank', 'stare', 'stark', 'stars', 'start', 'state', 'stave', 'stays', 'stead', 'steak', 'steal', 'steam', 'steed', 'steel', 'steep', 'steer', 'stems', 'steps', 'stern', 'stews', 'stick', 'stiff', 'stile', 'still', 'sting', 'stink', 'stint', 'stirs', 'stock', 'stoic', 'stole', 'stone', 'stony', 'stood', 'stool', 'stoop', 'stops', 'store', 'stork', 'storm', 'story', 'stout', 'stove', 'strap', 'straw', 'stray', 'strew', 'strip', 'strut', 'stuck', 'studs', 'study', 'stuff', 'stump', 'stung', 'stunt', 'style', 'suave', 'sucks', 'sugar', 'suing', 'suite', 'suits', 'sulks', 'sulky', 'sully', 'sunny', 'surer', 'surge', 'surly', 'swain', 'swamp', 'swans', 'sward', 'swarm', 'sways', 'swear', 'sweat', 'sweep', 'sweet', 'swell', 'swept', 'swift', 'swill', 'swims', 'swine', 'swing', 'swirl', 'swish', 'swoon', 'swoop', 'sword', 'swore', 'sworn', 'swung', 'synod', 'syrup', 'tabby', 'table', 'taboo', 'tacit', 'tacks', 'tails', 'taint', 'taken', 'takes', 'tales', 'talks', 'tally', 'talon', 'tamed', 'tamer', 'tanks', 'taper', 'tapes', 'tardy', 'tares', 'tarry', 'tarts', 'tasks', 'taste', 'tasty', 'taunt', 'tawny', 'taxed', 'taxes', 'teach', 'teams', 'tears', 'tease', 'teems', 'teens', 'teeth', 'tells', 'tempi', 'tempo', 'temps', 'tends', 'tenet', 'tenor', 'tense', 'tenth', 'tents', 'tepee', 'tepid', 'terms', 'terse', 'tests', 'testy', 'texts', 'thank', 'theft', 'their', 'theme', 'there',
            'these', 'thick', 'thief', 'thigh', 'thine', 'thing', 'think', 'third', 'thong', 'thorn', 'those', 'three', 'threw', 'throb', 'throe', 'thumb', 'thump', 'thyme', 'tiara', 'tibia', 'ticks', 'tidal', 'tides', 'tiers', 'tiger', 'tight', 'tilde', 'tiled', 'tiles', 'tills', 'tilts', 'timed', 'times', 'timid', 'tinge', 'tints', 'tipsy', 'tired', 'tires', 'tithe', 'title', 'toads', 'toast', 'today', 'toddy', 'toils', 'token', 'tolls', 'tombs', 'tomes', 'toned', 'tones', 'tongs', 'tonic', 'tools', 'tooth', 'topaz', 'topic', 'toque', 'torch', 'torso', 'torts', 'total', 'totem', 'touch', 'tough', 'tours', 'towed', 'towel', 'tower', 'towns', 'toxic', 'toyed', 'trace', 'track', 'tract', 'trade', 'trail', 'train', 'trait', 'tramp', 'trams', 'traps', 'trash', 'trays', 'tread', 'treat', 'treed', 'trees', 'trend', 'tress', 'triad', 'trial', 'tribe', 'trice', 'trick', 'tried', 'tries', 'trill', 'tripe', 'trips', 'trite', 'troll', 'troop', 'troth', 'trots', 'trout', 'truce', 'truck', 'truer', 'truly', 'trump', 'trunk', 'truss', 'trust', 'truth', 'tryst', 'tubes', 'tufts', 'tulip', 'tulle', 'tuned', 'tunes', 'tunic', 'turns', 'tusks', 'tutor', 'twain', 'twang', 'tweed', 'twice', 'twigs', 'twine', 'twins', 'twirl', 'twist', 'tying', 'typed', 'types', 'udder', 'ulcer', 'ultra', 'uncle', 'uncut', 'under', 'undid', 'undue', 'unfit', 'union', 'unite', 'units', 'unity', 'unsay', 'untie', 'until', 'upper', 'upset', 'urban', 'urged', 'urges', 'urine', 'usage', 'users', 'usher', 'using', 'usual', 'usurp', 'usury', 'utter', 'vague', 'vales', 'valet', 'valid', 'value', 'valve', 'vanes', 'vapid', 'vases', 'vault', 'vaunt', 'veils', 'veins', 'veldt', 'venal', 'venom', 'vents', 'venue', 'verbs', 'verge', 'verse', 'verve', 'vests', 'vexed', 'vexes', 'vials', 'vicar', 'vices', 'video', 'views', 'vigil', 'viler', 'villa', 'vines', 'viola', 'viper', 'virus', 'visit', 'visor', 'vista', 'vital', 'vivid', 'vixen', 'vizor', 'vocal', 'vodka', 'vogue', 'voice', 'voile', 'volts', 'vomit', 'voted', 'voter', 'votes', 'vouch', 'vowed', 'vowel', 'vying', 'waded', 'wafer', 'wafts', 'waged', 'wager', 'wages', 'wagon', 'waifs', 'wails', 'waist', 'waits', 'waive', 'waked', 'waken', 'wakes',
            'walks', 'walls', 'waltz', 'wands', 'waned', 'wanes', 'wants', 'wards', 'wares', 'warms', 'warns', 'warts', 'wasps', 'waste', 'watch', 'water', 'waved', 'waver', 'waves', 'waxed', 'waxen', 'waxes', 'wears', 'weary', 'weave', 'wedge', 'weeds', 'weedy', 'weeks', 'weeps', 'weigh', 'weird', 'welch', 'wells', 'wench', 'whack', 'whale', 'wharf', 'wheat', 'wheel', 'whelp', 'where', 'which', 'whiff', 'whims', 'whine', 'whips', 'whirl', 'whirr', 'whisk', 'whist', 'white', 'whole', 'whoop', 'whore', 'whose', 'wicks', 'widen', 'wider', 'widow', 'width', 'wield', 'wight', 'wilds', 'wiles', 'wills', 'wince', 'winch', 'winds', 'windy', 'wines', 'wings', 'winks', 'wiped', 'wipes', 'wired', 'wires', 'wiser', 'wisps', 'witch', 'witty', 'wives', 'woman', 'women', 'woods', 'woody', 'wooed', 'wooer', 'words', 'wordy', 'works', 'world', 'worms', 'worry', 'worse', 'worst', 'worth', 'would', 'wound', 'wrack', 'wraps', 'wrapt', 'wrath', 'wreak', 'wreck', 'wrest', 'wring', 'wrist', 'write', 'writs', 'wrong', 'wrote', 'wroth', 'yacht', 'yards', 'yarns', 'yawns', 'yearn', 'years', 'yeast', 'yells', 'yelps', 'yoked', 'yokes', 'yolks', 'young', 'yours', 'youth', 'zebra', 'zones',
            'Abalone', 'Abandon', 'Ability', 'Abolish', 'Abdomen', 'Abraham', 'Abyssal', 'Academy', 'Account', 'Achieve', 'Acidity', 'Acquire', 'Acrobat', 'Acronym', 'Acrylic', 'Actress', 'Adaptor', 'Address', 'Adjourn', 'Admiral', 'Advance', 'Advisor', 'Aerator', 'Aerosol', 'Affable', 'Afflict', 'Affront', 'African', 'Against', 'Ageless', 'Agendum', 'Agility', 'Agonize', 'Ailment', 'Airdrop', 'Airfare', 'Airflow', 'Airfoil', 'Airhead', 'Airlift', 'Airline', 'Airmail', 'Airplay', 'Airport', 'Airship', 'Airshow', 'Airsick', 'Airtime', 'Airwave', 'Alamode', 'Alchemy', 'Alcohol', 'Alfalfa', 'Algebra', 'Alfredo', 'Alimony', 'Alkalic', 'Allergy', 'Almanac', 'Already', 'Alright', 'Alumnus', 'Alveoli', 'Amadeus', 'Amateur', 'Amazing', 'Ambient', 'Ambling', 'Amenity', 'America', 'Amiable', 'Ammonia', 'Amnesia', 'Amnesty', 'Amplify', 'Anagram', 'Analogy', 'Analyst', 'Analyze', 'Anarchy', 'Anatomy', 'Anchovy', 'Ancient', 'Android', 'Anemone', 'Angelic', 'Angrier', 'Angrily', 'Anguish', 'Angular', 'Animals', 'Animate', 'Annuity', 'Answers', 'Antacid', 'Antenna', 'Anthill', 'Anthrax', 'Antifog', 'Antique', 'Antonym', 'Anybody', 'Anymore', 'Anytime', 'Anxiety', 'Anxious', 'Apology', 'Apostle', 'Appease', 'Applaud', 'Appoint', 'Approve', 'Apricot', 'Aquatic', 'Aquifer', 'Archery', 'Archive', 'Archway', 'Arduous', 'Armband', 'Arousal', 'Arraign', 'Arrange', 'Arrival', 'Artists', 'Artwork', 'Ascetic', 'Ashtray', 'Asphalt', 'Aspirin', 'Assault', 'Astride', 'Atheist', 'Athlete', 'Attempt', 'Attract', 'Auction', 'Audible', 'Augment', 'Austria', 'Autopsy', 'Average', 'Aviator', 'Avocado', 'Awaking', 'Awesome', 'Awkward', 'Babysit', 'Backlit', 'Backlog', 'Backrub', 'Badland', 'Baggage', 'Bailout', 'Balance', 'Ballboy', 'Balloon', 'Baloney', 'Bananas', 'Bandage', 'Bandaid', 'Bangkok', 'Bargain', 'Bashful', 'Bastard', 'Battery', 'Beatles', 'Bedroom', 'Beehive', 'Believe', 'Beneath', 'Benefit', 'Berries', 'Between', 'Bicycle', 'Bifocal', 'Billion', 'Bipolar', 'Biscuit', 'Blocker', 'Blossom', 'Blowout', 'Bluejay', 'Blueray', 'Boycott', 'Bravery', 'Breaker', 'Brewery', 'British', 'Brownie', 'Browser', 'Buffalo', 'Builder', 'Bulldog', 'Burgers', 'Burnout', 'Burrito', 'Cabinet',
            'Calcium', 'Camelot', 'Campain', 'Capital', 'Capitol', 'Captain', 'Caption', 'Capture', 'Caravan', 'Carbarn', 'Cardoor', 'Careers', 'Careful', 'Caribou', 'Carkeys', 'Carrier', 'Cartoon', 'Cascade', 'Cassidy', 'Catfish', 'Caution', 'Central', 'Century', 'Certain', 'Chalice', 'Chamber', 'Changes', 'Channel', 'Chapter', 'Charger', 'Charity', 'Charlie', 'Cheaper', 'Cheater', 'Checker', 'Checkup', 'Cheddar', 'Cheerio', 'Cheetah', 'Cherish', 'Chicken', 'Chimney', 'Chipper', 'Choices', 'Choosey', 'Chopper', 'Chorale', 'Chowder', 'Circuit', 'Classes', 'Classic', 'Cleaner', 'Clinton', 'Closely', 'Clothes', 'Cockpit', 'Coconut', 'Coldest', 'Collage', 'Collect', 'College', 'Colonel', 'Combine', 'Combust', 'Comedic', 'Comfort', 'Comical', 'Command', 'Commend', 'Comment', 'Commode', 'Commune', 'Commute', 'Compact', 'Company', 'Compare', 'Compass', 'Compete', 'Compile', 'Complex', 'Compose', 'Compute', 'Comrade', 'Concave', 'Conceal', 'Concede', 'Conceit', 'Concent', 'Concept', 'Concern', 'Concert', 'Concise', 'Concord', 'Condemn', 'Condone', 'Conduct', 'Conduit', 'Confess', 'Confide', 'Confine', 'Confirm', 'Conform', 'Confuse', 'Congeal', 'Conical', 'Conifer', 'Conjoin', 'Conjure', 'Connect', 'Conquer', 'Console', 'Consort', 'Consult', 'Consume', 'Contact', 'Contain', 'Contend', 'Content', 'Contest', 'Context', 'Contour', 'Control', 'Convent', 'Convict', 'Cookies', 'Correct', 'Corrupt', 'Costume', 'Cottage', 'Council', 'Counter', 'Country', 'Couples', 'Courage', 'Cowgirl', 'Cowhide', 'Cracker', 'Crapper', 'Crawler', 'Crazily', 'Creator', 'Crewcut', 'Crimson', 'Cripple', 'Crouton', 'Crucify', 'Cruelty', 'Cruiser', 'Crunchy', 'Crusade', 'Crybaby', 'Crystal', 'Cubicle', 'Cuisine', 'Culprit', 'Culture', 'Culvert', 'Cumulus', 'Cupcake', 'Cuplike', 'Curator', 'Curious', 'Current', 'Cursive', 'Curtail', 'Curtain', 'Cushion', 'Custard', 'Custody', 'Cutback', 'Cuticle', 'Cutlery', 'Cutlets', 'Cyclone', 'Cynical', 'Daycare', 'Daytime', 'Decades', 'Deceive', 'Declare', 'Decibel', 'Decimal', 'Declare', 'Decline', 'Decoder', 'Decorum', 'Default', 'Defence', 'Defiant', 'Deficit', 'Deflate', 'Defrost', 'Defuser', 'Degrade', 'Degrees', 'Delight', 'Deliver', 'Deltoid', 'Demerit', 'Denmark',
            'Density', 'Dentist', 'Denture', 'Deplete', 'Deplore', 'Deposit', 'Depress', 'Deprive', 'Dervish', 'Descent', 'Deserve', 'Desktop', 'Despair', 'Despite', 'Despond', 'Dessert', 'Destain', 'Destiny', 'Destroy', 'Detract', 'Develop', 'Devilry', 'Devious', 'Dewdrop', 'Diamond', 'Diapers', 'Diction', 'Diecast', 'Digital', 'Dignity', 'Disable', 'Disavow', 'Disband', 'Discard', 'Discern', 'Discord', 'Discuss', 'Disdain', 'Disease', 'Diseuse', 'Disgust', 'Disjoin', 'Dislike', 'Dismast', 'Dismiss', 'Disobey', 'Dispart', 'Display', 'Disport', 'Dispose', 'Dispute', 'Disrate', 'Disrobe', 'Disrupt', 'Disseat', 'Distort', 'Disturb', 'Dissect', 'Distant', 'Distend', 'Distich', 'Distill', 'Diverse', 'Divided', 'Divorce', 'Doctors', 'Dollars', 'Dolphin', 'Doorway', 'Dormant', 'Draught', 'Dreamer', 'Drivers', 'Dryness', 'Durable', 'Dynamic', 'Earache', 'Earlier', 'Earlobe', 'Eastern', 'Eclipse', 'Economy', 'Educate', 'Egotism', 'Elastic', 'Elderly', 'Elegant', 'Element', 'Elevate', 'Embassy', 'Embrace', 'Emotion', 'Empathy', 'Empress', 'Enclose', 'Endless', 'Enforce', 'English', 'Enhance', 'Enlight', 'Envious', 'Eternal', 'Ethical', 'Equinox', 'Equator', 'Evasive', 'Exactly', 'Example', 'Excited', 'Expense', 'Experts', 'Explain', 'Explode', 'Explore', 'Express', 'Extinct', 'Extract', 'Extreme', 'Eyebrow', 'Eyelash', 'Faceoff', 'Factoid', 'Factors', 'Faculty', 'Failure', 'Fanclub', 'Fantasy', 'Farmboy', 'Farmers', 'Fashion', 'Fastest', 'Fatigue', 'Feature', 'Federal', 'Ferment', 'Ferried', 'Fiction', 'Fifteen', 'Fighter', 'Finally', 'Finance', 'Firedog', 'Firefly', 'Fireman', 'Fitness', 'Fixture', 'Flowers', 'Flulike', 'Flushot', 'Foolish', 'Footage', 'Forbear', 'Forearm', 'Foreign', 'Forever', 'Foreman', 'Forfeit', 'Forgive', 'Formula', 'Forsake', 'Fortune', 'Forward', 'Foxhole', 'Fragile', 'Frantic', 'Freezer', 'Freckle', 'Freedom', 'Freeway', 'Freight', 'Freshly', 'Friends', 'Frisbee', 'Fritter', 'Fumbled', 'Further', 'Gambler', 'Gameboy', 'Garages', 'Garbage', 'Gashose', 'Gastank', 'Gateway', 'General', 'Genesis', 'Generic', 'Genetic', 'Getaway', 'Giraffe', 'Glimpse', 'Glorify', 'Glucose', 'Goodbye', 'Gorilla', 'Governs', 'Gradual', 'Grammar', 'Grandma', 'Grandpa', 'Granite', 'Granola', 'Graphic', 'Gravity', 'Grocery', 'Habitat', 'Haircut',
            'Halibut', 'Happily', 'Harbour', 'Harding', 'Harvest', 'Hatchet', 'Hateful', 'Healthy', 'Heights', 'Helpful', 'Heroism', 'Herself', 'Highest', 'Highway', 'Himself', 'History', 'Holiday', 'Holland', 'Homeboy', 'Honesty', 'Hopeful', 'Hotcake', 'Hotdogs', 'Husband', 'Hydrant', 'Iceberg', 'Iceland', 'Icicles', 'Ideally', 'Idolize', 'Illicit', 'Illness', 'Imagine', 'Impound', 'Impress', 'Improve', 'Inboard', 'Inbound', 'Incense', 'Incisor', 'Incline', 'Inclose', 'Include', 'Incomes', 'Incubus', 'Indoors', 'Indulge', 'Infancy', 'Inferno', 'Infidel', 'Inflame', 'Inflate', 'Inflict', 'Ingrain', 'Ingrown', 'Inhaler', 'Inherit', 'Initial', 'Inkblot', 'Inkling', 'Inkwell', 'Inlayer', 'Inquire', 'Inquiry', 'Insects', 'Insider', 'Insight', 'Inspect', 'Inspire', 'Install', 'Instant', 'Instead', 'Instill', 'Insular', 'Insurer', 'Intense', 'Interim', 'Interns', 'Introit', 'Intrude', 'Intrust', 'Intwine', 'Invader', 'Invoice', 'Involve', 'Islamic', 'Islands', 'Isolate', 'Itemize', 'Jamaica', 'January', 'Jasmine', 'Jealous', 'Jewelry', 'Journey', 'Justice', 'Justify', 'Kennedy', 'Keyhole', 'Keynote', 'Kingdom', 'Kinship', 'Kitchen', 'Kittens', 'Kneecap', 'Lantern', 'Laundry', 'Lawsuit', 'Lawyers', 'Leaders', 'Learner', 'Leather', 'Lenscap', 'Lessons', 'Letters', 'Liberal', 'Liberty', 'Library', 'License', 'Lincoln', 'Lipread', 'Literal', 'Livable', 'Lobster', 'Logical', 'Lovable', 'Lovebug', 'Lullaby', 'Machine', 'Madison', 'Madness', 'Magical', 'Magnify', 'Mailbag', 'Mailbox', 'Mailman', 'Majesty', 'Malaria', 'Maldive', 'Manager', 'Mandate', 'Manners', 'Markers', 'Married', 'Massage', 'Massive', 'Mastery', 'Meander', 'Measure', 'Medical', 'Members', 'Menthol', 'Mercury', 'Mermaid', 'Message', 'Methane', 'Michael', 'Midterm', 'Migrant', 'Migrate', 'Militia', 'Million', 'Misdial', 'Misfile', 'Mislead', 'Misread', 'Missile', 'Mission', 'Mistake', 'Mixture', 'Mobster', 'Modesty', 'Monarch', 'Monitor', 'Monolog', 'Monsoon', 'Monster', 'Montage', 'Monthly', 'Moocher', 'Moonlit', 'Morally', 'Morning', 'Moronic', 'Mortify', 'Mortise', 'Mudflap', 'Mudflow', 'Muffler', 'Muffins', 'Mundane', 'Musical', 'Mustang', 'Mustard', 'Mystery', 'Mystify', 'Nametag', 'Napkins', 'Narcism', 'Nations', 'Natives', 'Natural', 'Naughty', 'Nearest', 'Nebular', 'Necktie', 'Needles', 'Neglect', 'Nervous',
            'Network', 'Neurons', 'Neutral', 'Neutron', 'Newborn', 'Newsboy', 'Niagera', 'Nickels', 'Nightly', 'Nirvana', 'Nitrate', 'Nocturn', 'Noisily', 'Nomadic', 'Nominal', 'Nonstop', 'Nostril', 'Notable', 'Notably', 'Nothing', 'Novelty', 'Noxious', 'Nuclear', 'Nucleus', 'Nudnick', 'Nullify', 'Numbers', 'Numeral', 'Nunlike', 'Nunnery', 'Nursery', 'Nurture', 'Nutcase', 'Obesity', 'Observe', 'Obvious', 'Octagon', 'Octopus', 'October', 'Offense', 'Operate', 'Opinion', 'Organic', 'Ottoman', 'Outback', 'Outcast', 'Outcome', 'Outdoor', 'Outrage', 'Outside', 'Overall', 'Package', 'Painful', 'Painter', 'Pajamas', 'Pandora', 'Panther', 'Paradox', 'Parents', 'Parties', 'Partner', 'Passion', 'Patient', 'Patriot', 'Payment', 'Peanuts', 'Penalty', 'Pennies', 'Pension', 'Percent', 'Perfect', 'Perform', 'Perfume', 'Persist', 'Phonics', 'Phrases', 'Physics', 'Picture', 'Pigears', 'Pigtail', 'Pilgrim', 'Pinball', 'Pintail', 'Pioneer', 'Plastic', 'Playful', 'Plunder', 'Politic', 'Pollute', 'Popcorn', 'Poptart', 'Popular', 'Postage', 'Postbox', 'Postman', 'Praises', 'Prebake', 'Preboil', 'Precede', 'Precise', 'Predict', 'Preempt', 'Preface', 'Preheat', 'Preload', 'Prelude', 'Premade', 'Premier', 'Premise', 'Premium', 'Prepaid', 'Prepare', 'Preppie', 'Prequel', 'Presale', 'Present', 'Preshow', 'Presoak', 'Presume', 'Preteen', 'Pretend', 'Pretest', 'Pretzel', 'Prevail', 'Prevent', 'Preverb', 'Preview', 'Prewash', 'Preworn', 'Preying', 'Pricier', 'Prickly', 'Primage', 'Primary', 'Primate', 'Printer', 'Privacy', 'Private', 'Privies', 'Probate', 'Problem', 'Proceed', 'Process', 'Proctor', 'Procure', 'Prodigy', 'Produce', 'Product', 'Profane', 'Profess', 'Profile', 'Profuse', 'Progeny', 'Program', 'Project', 'Prolate', 'Proline', 'Prolong', 'Promise', 'Promote', 'Pronate', 'Pronoun', 'Propane', 'Prophet', 'Propose', 'Prorate', 'Prosody', 'Prosper', 'Protect', 'Protein', 'Protest', 'Protons', 'Proudly', 'Proverb', 'Provide', 'Provoke', 'Provost', 'Prowess', 'Prowler', 'Proxies', 'Prudent', 'Puberty', 'Publish', 'Pumpkin', 'Puppies', 'Purpose', 'Pursuit', 'Pyramid', 'Qualify', 'Quality', 'Quantum', 'Quarrel', 'Quarter', 'Queenly', 'Queerly', 'Quicken', 'Quicker', 'Quickly', 'Quieter', 'Quietly', 'Quilter', 'Quinine', 'Quintet', 'Quitter', 'Raccoon', 'Racecar', 'Raceway', 'Radiant', 'Radical', 'Ragtime', 'Ragweed', 'Railcar', 'Rainbow', 'Rambler',
            'Rampant', 'Rampart', 'Rancher', 'Raisins', 'Ransack', 'Rapidly', 'Rapport', 'Rapture', 'Rattler', 'Ravioli', 'Reactor', 'Reality', 'Realize', 'Rebuild', 'Receipt', 'Receive', 'Recheck', 'Reclaim', 'Recline', 'Recover', 'Rectify', 'Recycle', 'Redbull', 'Redcoat', 'Redhead', 'Redline', 'Redneck', 'Redness', 'Redtail', 'Reducer', 'Redwood', 'Referee', 'Reflect', 'Refocus', 'Refract', 'Refrain', 'Refresh', 'Refugee', 'Refusal', 'Refutal', 'Regatta', 'Regimen', 'Regular', 'Reissue', 'Rejoice', 'Related', 'Relaxer', 'Relearn', 'Release', 'Remount', 'Reptile', 'Rescued', 'Rescuer', 'Reserve', 'Respect', 'Respond', 'Restate', 'Restore', 'Reteach', 'Retrain', 'Reunion', 'Reunite', 'Revolve', 'Ripcurl', 'Riptide', 'Riviera', 'Rosebud', 'Routine', 'Rowboat', 'Rugrats', 'Sabbath', 'Sandman', 'Sarcasm', 'Satisfy', 'Scandal', 'Scenery', 'Scholar', 'Seabass', 'Seabird', 'Seafood', 'Seafowl', 'Seagull', 'Sealant', 'Seaport', 'Seasick', 'Seaside', 'Seasons', 'Seawall', 'Seaward', 'Seaweed', 'Secrecy', 'Section', 'Secular', 'Secured', 'Serious', 'Selfish', 'Sellout', 'Sensors', 'Servant', 'Service', 'Setback', 'Settler', 'Seventy', 'Several', 'Shelter', 'Sheriff', 'Sherman', 'Shifter', 'Shirley', 'Shooter', 'Shorter', 'Sidearm', 'Sincere', 'Sitdown', 'Sixteen', 'Skijump', 'Skimask', 'Skipole', 'Skypark', 'Slavery', 'Smarter', 'Smuggle', 'Snowman', 'Snuggle', 'Society', 'Soldier', 'Someday', 'Speaker', 'Special', 'Species', 'Sponsor', 'Stadium', 'Stamina', 'Standup', 'Staples', 'Station', 'Storage', 'Stories', 'Stirfry', 'Stirrup', 'Streams', 'Strides', 'Student', 'Subject', 'Subsist', 'Subtext', 'Succeed', 'Success', 'Sucrose', 'Suggest', 'Suicide', 'Sulphur', 'Summary', 'Sunbath', 'Sunbelt', 'Sunbeam', 'Sunbelt', 'Sunburn', 'Sundays', 'Sundeck', 'Sundial', 'Sundown', 'Sunfish', 'Sunglow', 'Sunlamp', 'Sunland', 'Sunlike', 'Sunmaid', 'Sunrise', 'Sunroof', 'Sunroom', 'Sunsets', 'Sunspot', 'Support', 'Suppose', 'Supreme', 'Surgeon', 'Surgery', 'Survive', 'Suspend', 'Sweater', 'Swimmer', 'Swollen', 'Symptom', 'Tablets', 'Tabloid', 'Tadpole', 'Talents', 'Tangent', 'Tangled', 'Taxcuts', 'Teacher', 'Teenage', 'Tension', 'Tequila', 'Termite', 'Terrify', 'Testify', 'Textile', 'Theatre', 'Therapy', 'Thermos', 'Thinker', 'Thirsty', 'Thought', 'Thunder', 'Timeout', 'Tubacco', 'Toenail', 'Toering', 'Tonight', 'Tonnage', 'Topanga', 'Topdeck', 'Topless', 'Topload', 'Topples', 'Toprack', 'Topside',
            'Topsoil', 'Tornado', 'Torture', 'Tourist', 'Towboat', 'Towhead', 'Tractor', 'Traitor', 'Transit', 'Treetop', 'Tribute', 'Trouble', 'Trouser', 'Trucker', 'Trumpet', 'Tuesday', 'Tunisia', 'Twinkle', 'Twister', 'Typhoid', 'Typical', 'Tyranny', 'Unhappy', 'Unheard', 'Unhinge', 'Unhitch', 'Unicorn', 'Unified', 'Uniform', 'Unitard', 'Unitary', 'Unkempt', 'Unknown', 'Unlatch', 'Unlearn', 'Unleash', 'Unlevel', 'Unloose', 'Unlucky', 'Unquote', 'Unravel', 'Unready', 'Unscrew', 'Unstack', 'Unusual', 'Unwound', 'Unwoven', 'Updraft', 'Upfront', 'Upgrade', 'Upright', 'Upscale', 'Upstair', 'Upstate', 'Upsurge', 'Upswell', 'Upswept', 'Upswing', 'Uptight', 'Uranium', 'Urgency', 'Urinary', 'Urinate', 'Urology', 'Usually', 'Utensil', 'Utility', 'Utopian', 'Vacancy', 'Vaccine', 'Vagrant', 'Vaguely', 'Valance', 'Valuate', 'Valleys', 'Vampire', 'Vanilla', 'Vanload', 'Vanpool', 'Variant', 'Variety', 'Vehicle', 'Velvety', 'Venison', 'Venture', 'Verdict', 'Version', 'Vibrate', 'Viceroy', 'Victory', 'Village', 'Vintage', 'Violate', 'Violent', 'Visitor', 'Volcano', 'Waffles', 'Walnuts', 'Warbler', 'Warfare', 'Warrior', 'Washers', 'Wealthy', 'Weather', 'Webcast', 'Website', 'Webster', 'Weekend', 'Welcome', 'Welfare', 'Western', 'Wetness', 'Wetsuit', 'Whoever', 'Windows', 'Winners', 'Wipeout', 'Wiseman', 'Without', 'Witness', 'Worldly', 'Worship', 'Wrestle', 'Wronged', 'Zealous']
        // All Possible words in the scrambler
    }
    letters_Scrambled = getWord();
}
let theword, score = 0;
function getWord() {
    theword = words[Math.floor(Math.random() * words.length)];
    // Randomly selecting the word from the possible values given in the array
    text = theword;  // The message displayed
    chars = `abcdefghijklmnopqrstuvwxyz'",ABCDEFGHIJKLMNOPQRSTUVWXYZ `;  // All possible Charactrers
    scale = 20;  // Font size and overall scale
    breaks = 0.003;  // Speed loss per frame
    endSpeed = 0.05;  // Speed at which the letter stops
    firstLetter = 220;  // Number of frames untill the first letter stopps (60 frames per second)
    delay = 40;  // Number of frames between letters stopping



    canvas = document.querySelector('canvas');
    ctx = canvas.getContext('2d');

    // Splitting the letters in the word into individual characters
    text = text.split('');
    // Scrambling the letters using math to make it kind of random
    text = text.sort(() => 0.5 - Math.random());
    // Checking if theword and the letters are the same
    if (text.join('') == theword) {
        text.sort(() => 0.5 - Math.random());
    }
    chars = chars.split('');
    charMap = [];
    offset = [];
    offsetV = [];

    for (var i = 0; i < chars.length; i++) {
        charMap[chars[i]] = i;
    }

    for (var i = 0; i < text.length; i++) {
        var f = firstLetter + delay * i;
        offsetV[i] = endSpeed + breaks * f;
        offset[i] = -(1 + f) * (breaks * f + 2 * endSpeed) / 2;
    }

    (onresize = function () {
        canvas.width = canvas.clientWidth;
        canvas.height = canvas.clientHeight;
    })();

    requestAnimationFrame(loop = function () {
        ctx.setTransform(1, 0, 0, 1, 0, 0);
        ctx.clearRect(0, 0, canvas.width, canvas.height);
        ctx.globalAlpha = 1;
        ctx.fillStyle = '#622';
        ctx.fillRect(0, (canvas.height - scale) / 2, canvas.width, scale);
        for (var i = 0; i < text.length; i++) {
            ctx.fillStyle = '#ccc';
            ctx.textBaseline = 'middle';
            ctx.textAlign = 'center';
            ctx.setTransform(1, 0, 0, 1, Math.floor((canvas.width - scale * (text.length - 1)) / 2), Math.floor(canvas.height / 2));
            var o = offset[i];
            while (o < 0) o++;
            o %= 1;
            var h = Math.ceil(canvas.height / 2 / scale)
            for (var j = -h; j < h; j++) {
                var c = charMap[text[i]] + j - Math.floor(offset[i]);
                while (c < 0) c += chars.length;
                c %= chars.length;
                var s = 1 - Math.abs(j + o) / (canvas.height / 2 / scale + 1)
                ctx.globalAlpha = s
                ctx.font = scale * s + 'px Helvetica'
                ctx.fillText(chars[c], scale * i, (j + o) * scale);
            }
            offset[i] += offsetV[i];
            offsetV[i] -= breaks;
            if (offsetV[i] < endSpeed) {
                offset[i] = 0;
                offsetV[i] = 0;
            }
        }

        requestAnimationFrame(loop);
    });
}
wordInput()
function name() {
    const enterKey = document.getElementById('name');
    enterKey.addEventListener("keydown", (event) => {
        if (event.key === "Enter") {
            alert("Posted Score to Leaderboard");
            let name1 = document.getElementById('name').value;
            localStorage.setItem('Name', name1);
        }

    })
}

function wordInput() {
    const enterKey = document.getElementById('scrambled-word');
    enterKey.addEventListener("keydown", (event) => {
        if (event.key === "Enter") {
            let answer = document.getElementById('scrambled-word').value
            // Makes answer equal to whatever they put
            if (answer == theword) {
                alert('Congratulations, You got it Right!');
                score += theword.length;
                return score;
            }
            else {
                alert(`You suck lol: ${theword}`);
            }
            getWord()
        }

    })
}

// if you get it right, you are right. If not then you suck
// IDEAS
// Add scoreboard
// Need to make it so script resets when you get it wrong
// Showing the user the answer after they get it wrong
// New Difficulties that give more points
// Timer
// Health counter???
/* -------------------------------------- */
/* ------------  Settings  -------------- */
/* -------------------------------------- */

